services:
  web:
    image: php:8.2-apache
    container_name: lamp_web
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y libpng-dev libonig-dev libxml2-dev default-mysql-client &&
        docker-php-ext-install pdo_mysql mysqli gd &&
        a2enmod rewrite &&
        apache2-foreground
      "

  mysql:
    image: mysql:8.0
    container_name: lamp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  telegram_bot:
    image: python:3.11-alpine
    container_name: python_telegram_bot
    volumes:
      - ./bot:/app
    working_dir: /app
    environment:
      - DB_HOST=mysql
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=myapp
      - TELEGRAM_BOT_TOKEN=YOUR_BOT_TOKEN_HERE
      - TELEGRAM_ADMIN_ID=0
      - LOG_LEVEL=INFO
    command: >
      sh -c "
        pip install --upgrade pip
        pip install -r requirements.txt &&
        python telegram_bot.py
      "
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge